### PR TITLE
feat(optionalButton): optional button for the keyboard view

### PR DESCRIPTION
**Pull request by sahilkhan99**
user can use optional button such as
- Reset the password
- forgot password to redirect to other screen etc

### CODE REVIEW

**Comment by talut** [comment]
@sahilkhan99 Thanks, I'll review as soon as possible.

**Comment by talut** [comment]
@sahilkhan99  Thanks.

**Comment by sahilkhan99** [comment]
@talut you are welcome.

**Comment by devfordays** [comment]
Hey @talut @sahilkhan99 thanks for such a nice package.   Has the readme been updated to account for the custom button on the right side ?! 
I'm not so sure how to use it :/

**Pull request merged**
